import type { Metadata } from "next";
import MainLayout from "@/app/(components)/MainLayout";
import "./globals.css";
import Link from "next/link";
import {
    ClerkProvider,
    SignedIn,
    SignedOut,
    SignInButton,
} from "@clerk/nextjs";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html>
            <body>
                <MainLayout>{children}</MainLayout>
            </body>
        </html>
    );
}
